ALTER TABLE tenants ADD COLUMN IF NOT EXISTS balance_usd NUMERIC(12,4) NOT NULL DEFAULT 0;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS allowed_models TEXT[];
ALTER TABLE usage_daily ADD COLUMN IF NOT EXISTS cost_usd NUMERIC(12,4) NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS cost_usd NUMERIC(12,4) NOT NULL DEFAULT 0;
